const ActionTypes = {
    SET_HOME_SYMBOLS: 'SET_HOME_SYMBOLS',
    SET_FAVORITE_SYMBLOS: 'SET_FAVORITE_SYMBLOS',
    SET_SYMBOLS_DATA: 'SET_SYMBOLS_DATA',
    SET_IS_LOGGED_IN: 'SET_IS_LOGGED_IN',
    SET_SELECTED_SYMBOL: 'SET_SELECTED_SYMBOL'
};

export default ActionTypes;
